### ISSUE TITLE
error when running npm start

### ISSUE THREAD

**Issue by BloodOnTop** [eyalmichon/TheMultitasker#2]
imagineSecrets.userAgent = randomUserAgent();
                         ^

TypeError: Cannot set properties of undefined (setting 'userAgent')
    at Object.<anonymous> (C:\Users\tomer\Documents\bots\multitasker\TheMultitasker-1.8.29\handler\lib\imagine.js:213:26)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\Users\tomer\Documents\bots\multitasker\TheMultitasker-1.8.29\handler\lib\index.js:25:19)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\Users\tomer\Documents\bots\multitasker\TheMultitasker-1.8.29\handler\lib\commands\admin.js:3:20)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\Users\tomer\Documents\bots\multitasker\TheMultitasker-1.8.29\handler\lib\commands\index.js:3:19)

Node.js v18.14.2

**Comment by BloodOnTop** [comment]
nvm i am dumb

**Comment by eyalmichon** [comment]
i'll update the docs later

**Comment by BloodOnTop** [comment]
Yea im just stupid

**Comment by BloodOnTop** [comment]
can i contact you by any chance?

**Comment by BloodOnTop** [comment]
?
